# Generated by Django 4.0.6 on 2022-08-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedNcrna',
            fields=[
                ('annotated_ncrna_element_id', models.CharField(max_length=190, primary_key=True, serialize=False)),
                ('annotated_ncrna_name', models.CharField(blank=True, max_length=190, null=True)),
                ('related_srna_name', models.CharField(blank=True, max_length=190, null=True)),
            ],
            options={
                'db_table': 'annotated_ncrna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('element_id', models.CharField(max_length=190, primary_key=True, serialize=False)),
                ('element_type', models.CharField(max_length=190)),
            ],
            options={
                'db_table': 'elements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoTerms',
            fields=[
                ('go_term_id', models.CharField(max_length=190, primary_key=True, serialize=False)),
                ('go_term_name', models.CharField(blank=True, max_length=190, null=True)),
                ('go_term_type', models.CharField(blank=True, max_length=190, null=True)),
                ('go_term_def', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'go_terms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrowthConditions',
            fields=[
                ('full_condition_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_condition_name', models.CharField(max_length=190)),
            ],
            options={
                'db_table': 'growth_conditions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('module_id', models.CharField(max_length=190, primary_key=True, serialize=False)),
                ('module_name', models.CharField(blank=True, max_length=190, null=True)),
                ('enrich_utr_qval', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('enrich_srna_qval', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('mycobrowser_category_enrichment', models.CharField(blank=True, max_length=190, null=True)),
            ],
            options={
                'db_table': 'modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('relation_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_match_score', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'relations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('sample_id', models.CharField(max_length=190, primary_key=True, serialize=False)),
                ('dataset_source', models.CharField(blank=True, max_length=190, null=True)),
                ('total_reads', models.IntegerField(blank=True, null=True)),
                ('mapped_reads', models.IntegerField(blank=True, null=True)),
                ('instrument', models.CharField(blank=True, max_length=190, null=True)),
            ],
            options={
                'db_table': 'samples',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SummedGrowthConditions',
            fields=[
                ('summed_condition_id', models.AutoField(primary_key=True, serialize=False)),
                ('summed_condition_name', models.CharField(max_length=190)),
            ],
            options={
                'db_table': 'summed_growth_conditions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cds',
            fields=[
                ('cds_element', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='searcher.elements')),
                ('cds_name', models.CharField(blank=True, max_length=190, null=True)),
                ('mycobroswer_functional_category', models.CharField(blank=True, max_length=190, null=True)),
                ('go_term_mol', models.CharField(blank=True, max_length=255, null=True)),
                ('go_term_bio', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleCorrelation',
            fields=[
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='searcher.modules')),
                ('raw_cor', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('p_adjusted_cor', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'module_correlation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Srna',
            fields=[
                ('srna_element', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='srna_element', serialize=False, to='searcher.elements')),
                ('srna_name', models.CharField(blank=True, max_length=190, null=True)),
                ('seq_start', models.IntegerField()),
                ('seq_end', models.IntegerField()),
                ('strand', models.TextField()),
                ('tss', models.IntegerField()),
                ('intergenic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'srna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utr',
            fields=[
                ('utr_element', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='utr_element', serialize=False, to='searcher.elements')),
                ('seq_start', models.IntegerField()),
                ('seq_end', models.IntegerField()),
                ('strand', models.TextField()),
                ('tss', models.IntegerField()),
                ('downstream_gene_element_id', models.CharField(blank=True, max_length=190, null=True)),
                ('predicted_utr_name', models.CharField(blank=True, max_length=190, null=True)),
                ('independent', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utr',
                'managed': False,
            },
        ),
    ]
